language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
  - "pip install -e ."
  - "pip install coveralls"
script:
  # No flake8 yet.
  # - "flake8 sharepad"
  - "py.test --cov=sharepad sharepad"
after_success:
  - "coveralls"
